"use client";

import { useEffect, useState } from "react";

export type BookingParticipant = { name: string; age?: number; relationship?: string };
export type FnbSelection = { productId: string; quantity: number };
type FnbProduct = { id: string; name: string; price: number; stock: number };

const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);

export default function BookingExtras({ maxParticipants, participants, setParticipants, fnbItems, setFnbItems }: { maxParticipants: number; participants: BookingParticipant[]; setParticipants: (value: BookingParticipant[]) => void; fnbItems: FnbSelection[]; setFnbItems: (value: FnbSelection[]) => void }) {
  const [products, setProducts] = useState<FnbProduct[]>([]);
  useEffect(() => { fetch("/api/fnb-products", { cache: "no-store" }).then((response) => response.json()).then((data) => setProducts(Array.isArray(data) ? data : [])).catch(() => setProducts([])); }, []);
  const addProduct = (productId: string) => { if (!productId) return; const current = fnbItems.find((item) => item.productId === productId); setFnbItems(current ? fnbItems.map((item) => item.productId === productId ? { ...item, quantity: Math.min(item.quantity + 1, products.find((product) => product.id === productId)?.stock ?? item.quantity + 1) } : item) : [...fnbItems, { productId, quantity: 1 }]); };
  const updateParticipant = (index: number, patch: Partial<BookingParticipant>) => setParticipants(participants.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  return <div className="mt-6 space-y-6 border-t border-black/5 pt-6">
    <div><h3 className="font-display text-lg font-bold text-marica-ink">Data peserta keluarga <span className="text-xs font-normal text-marica-ink-soft">(opsional)</span></h3><p className="mt-1 text-xs text-marica-ink-soft">Tambahkan nama anak dan pendamping agar registrasi lebih cepat di kasir.</p>
      <div className="mt-3 space-y-2">{participants.map((participant, index) => <div key={index} className="grid gap-2 sm:grid-cols-[1fr_80px_120px_auto]"><input required placeholder={`Nama peserta ${index + 1}`} value={participant.name} onChange={(event) => updateParticipant(index, { name: event.target.value })} className="rounded-xl border border-black/10 px-3 py-2 text-sm outline-none focus:border-marica-amber-dark" /><input type="number" min={0} max={120} placeholder="Usia" value={participant.age ?? ""} onChange={(event) => updateParticipant(index, { age: event.target.value ? Number(event.target.value) : undefined })} className="rounded-xl border border-black/10 px-3 py-2 text-sm outline-none focus:border-marica-amber-dark" /><input placeholder="Relasi" value={participant.relationship ?? ""} onChange={(event) => updateParticipant(index, { relationship: event.target.value })} className="rounded-xl border border-black/10 px-3 py-2 text-sm outline-none focus:border-marica-amber-dark" /><button type="button" onClick={() => setParticipants(participants.filter((_, itemIndex) => itemIndex !== index))} className="rounded-xl px-2 text-xs font-semibold text-red-600">Hapus</button></div>)}</div>
      {participants.length < maxParticipants && <button type="button" onClick={() => setParticipants([...participants, { name: "" }])} className="mt-3 text-sm font-semibold text-marica-amber-dark">+ Tambah peserta</button>}
    </div>
    <div><h3 className="font-display text-lg font-bold text-marica-ink">Pre-order makanan & minuman <span className="text-xs font-normal text-marica-ink-soft">(opsional)</span></h3><select defaultValue="" onChange={(event) => { addProduct(event.target.value); event.target.value = ""; }} className="mt-3 w-full rounded-xl border border-black/10 px-3 py-2 text-sm outline-none focus:border-marica-amber-dark"><option value="">Tambah menu F&B...</option>{products.filter((product) => product.stock > 0).map((product) => <option key={product.id} value={product.id}>{product.name} · {money(product.price)}</option>)}</select>{fnbItems.length > 0 && <div className="mt-3 space-y-2">{fnbItems.map((item) => { const product = products.find((candidate) => candidate.id === item.productId); return <div key={item.productId} className="flex items-center justify-between rounded-xl bg-marica-sky-light/40 px-3 py-2 text-sm"><span>{product?.name ?? item.productId}</span><div className="flex items-center gap-2"><button type="button" onClick={() => setFnbItems(item.quantity > 1 ? fnbItems.map((entry) => entry.productId === item.productId ? { ...entry, quantity: entry.quantity - 1 } : entry) : fnbItems.filter((entry) => entry.productId !== item.productId))} className="h-7 w-7 rounded-full bg-white">−</button><span>{item.quantity}</span><button type="button" onClick={() => addProduct(item.productId)} className="h-7 w-7 rounded-full bg-white">+</button></div></div>; })}</div>}</div>
  </div>;
}
