"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

type Reservation = { reservationNumber: string; status: string; partySize: number; totalPrice: number; visitDate: string; startTime: string; package: { name: string } };
const labels: Record<string, string> = { PAID: "Berhasil", PENDING_PAYMENT: "Menunggu pembayaran", CHECKED_IN: "Sudah check-in", CANCELLED: "Dibatalkan", EXPIRED: "Kedaluwarsa" };
const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);
export default function MyReservationsPage() { const [items, setItems] = useState<Reservation[]>([]); const [error, setError] = useState(""); useEffect(() => { fetch("/api/table-reservations?mine=1", { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (response.status === 401) { window.location.href = "/login?callbackUrl=/profil/reservasi"; return; } if (!response.ok) throw new Error(data.error); setItems(Array.isArray(data) ? data : []); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Reservasi gagal dimuat")); }, []); return <div className="flex min-h-screen flex-col bg-marica-sky-light/20 font-body"><Navbar /><main className="mx-auto w-full max-w-5xl flex-1 px-6 py-10"><div className="flex items-end justify-between gap-4"><div><h1 className="font-display text-3xl font-bold text-marica-ink">Reservasi Saya</h1><p className="mt-2 text-sm text-marica-ink-soft">Lihat jadwal dan QR reservasi meja.</p></div><Link href="/reservasi" className="rounded-full bg-marica-amber-dark px-4 py-2 text-sm font-semibold text-white">Reservasi baru</Link></div><div className="mt-8 space-y-4">{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{items.map((item) => <article key={item.reservationNumber} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-wide text-marica-amber-dark">{item.reservationNumber}</p><h2 className="mt-1 font-display text-xl font-bold text-marica-ink">{item.package.name}</h2><p className="mt-2 text-sm text-marica-ink-soft">{new Date(item.visitDate).toLocaleDateString("id-ID")} · {new Date(item.startTime).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })} WIB · {item.partySize} pemain</p></div><span className="h-fit rounded-full bg-marica-amber/20 px-3 py-1 text-xs font-semibold text-marica-amber-dark">{labels[item.status] ?? item.status}</span></div><div className="mt-5 flex items-center justify-between border-t border-black/5 pt-4 text-sm"><span className="text-marica-ink-soft">{money(item.totalPrice)}</span><Link href={`/reservasi/tiket/${item.reservationNumber}`} className="rounded-full bg-marica-amber-dark px-4 py-2 font-semibold text-white">Buka QR</Link></div></article>)}{!error && items.length === 0 && <p className="rounded-2xl bg-white p-8 text-center text-sm text-marica-ink-soft">Belum ada reservasi.</p>}</div></main><Footer /></div>; }
