"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import QRCode from "qrcode";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

type Reservation = { reservationNumber: string; qrToken: string; status: string; partySize: number; visitDate: string; startTime: string; endTime: string; package: { name: string } };
export default function ReservationTicketPage() { const { reservationNumber } = useParams<{ reservationNumber: string }>(); const [item, setItem] = useState<Reservation | null>(null); const [qr, setQr] = useState(""); const [error, setError] = useState(""); useEffect(() => { fetch(`/api/table-reservations/${encodeURIComponent(reservationNumber)}`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setItem(data); if (data.qrToken) setQr(await QRCode.toDataURL(data.qrToken)); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "QR reservasi gagal dimuat")); }, [reservationNumber]); return <div className="flex min-h-screen flex-col bg-marica-sky-light/20 font-body"><Navbar /><main className="mx-auto w-full max-w-2xl flex-1 px-6 py-10"><Link href="/profil/reservasi" className="text-sm font-semibold text-marica-amber-dark">← Kembali ke Reservasi Saya</Link>{error ? <p className="mt-8 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p> : item && <article className="mt-6 rounded-3xl bg-white p-6 text-center shadow-sm sm:p-10"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-marica-amber-dark">QR Reservasi</p><h1 className="mt-3 font-display text-3xl font-bold text-marica-ink">{item.package.name}</h1><p className="mt-3 text-sm text-marica-ink-soft">{new Date(item.visitDate).toLocaleDateString("id-ID", { dateStyle: "full" })}<br />{new Date(item.startTime).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })} - {new Date(item.endTime).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })} WIB<br />{item.partySize} pemain · {item.reservationNumber}</p>{["PAID", "CHECKED_IN"].includes(item.status) && qr ? <img src={qr} alt="QR reservasi meja" className="mx-auto mt-6 h-64 w-64" /> : <p className="mt-8 rounded-xl bg-marica-sky-light/40 p-4 text-sm text-marica-ink-soft">QR akan aktif setelah pembayaran berhasil.</p>}<p className="mt-5 text-xs text-marica-ink-soft">Tunjukkan QR ini kepada kasir saat datang.</p></article>}</main><Footer /></div>; }
